### ISSUE TITLE
Unstarted torrent will disappear after restart

### ISSUE THREAD

**Issue by thumbsized** [picotorrent/picotorrent#682] opened 2019-01-20 23:02 UTC
When I add new torrent and I don't start it and I restart picotorrent the torrent will no longer be shown in the list.

**Comment by vktr** [comment] 2019-01-21 05:53
Strange - can you give me a step by step on how you reproduce it?

**Comment by vktr** [comment] 2019-03-19 10:37
I can't reproduce it in #672 so I'm closing this for now.

**Closed by vktr** 2019-03-19 10:37 UTC

**Comment by thumbsized** [comment] 2019-07-11 17:47
Happened to me again. I think it is the same as #686
