### ISSUE TITLE
After the download is complete, the download speed is still displayed for about 60 seconds

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#782] opened 2019-12-21 20:24 UTC
After the download is completed, the download speed is still displayed for about 60 seconds, although the file has already been fully downloaded, and there can be no download speed. Please fix this problem.
<details>
<summary>Video</summary>

[screencast-mapeditor.yandex.com-2019.12.21-13_38_06.zip](https://github.com/picotorrent/picotorrent/files/3991793/screencast-mapeditor.yandex.com-2019.12.21-13_38_06.zip)

</details>

**Comment by VideoPlayerCode** [comment] 2019-12-22 02:07
Duplicate of #769

**Comment by vktr** [comment] 2019-12-22 13:01
This will be fixed when #750 gets merged.

**Comment by Rakleed** [comment] 2019-12-22 13:10
@vktr and if I downloaded from [here](https://ci.appveyor.com/project/picotorrent/picotorrent/builds/29476734/job/ycctoaj1be2x5qgk/artifacts), is [this PR](https://github.com/picotorrent/picotorrent/pull/750) not included in this build?

**Comment by vktr** [comment] 2019-12-22 13:11
@Rakleed That link points to the latest AppVeyor build for that PR, so everything in that PR is included in there.

**Comment by Rakleed** [comment] 2019-12-22 13:15
I installed the [latest build from AppVeyor](https://ci.appveyor.com/project/picotorrent/picotorrent/builds/29476734/job/ycctoaj1be2x5qgk/artifacts), and I'm still observing the problem that I described above.

**Comment by Rakleed** [comment] 2019-12-22 13:16
@vktr I installed the latest build from AppVeyor, and I'm still observing the problem that I described above.

**Comment by vktr** [comment] 2019-12-22 13:19
@Rakleed Yeah, I jumped the gun a bit, we only display the `-` for paused torrents, but it should be for download rate when a torrent as a progress of 100% as well. My bad. I'll make sure to fix this.

**Comment by VideoPlayerCode** [comment] 2020-01-10 08:04
Thanks @vktr for the 0.18 release. I am really happy that I'm sticking with this client. Getting better and better, and already has the best GUI of all clients!

And yeah, I see the code change which returns "-" whenever a torrent is in a paused state. It's a good step but read https://github.com/picotorrent/picotorrent/issues/769 for some suggestions on how to fix the problem when the torrent has finished download/uploading but isn't paused.

**Closed** 2020-02-14 23:26 UTC
