### ISSUE TITLE
Wrong icon in the start menu

### ISSUE THREAD

**Issue by dertuxmalwieder** [PicoTorrent/PicoTorrent#349] opened 2016-11-06 04:52 UTC
It seems like PicoTorrent does not *export* its icon: The start menu icon as well as the "pinned" icon (in earlier versions when I could still pin PicoTorrent to the taskbar...) is the default Windows Application icon...?

**Comment by vktr** [comment] 2016-11-06 13:20
<img width="282" alt="screenshot 2016-11-06 14 19 40" src="https://cloud.githubusercontent.com/assets/1491824/20038025/1336dee2-a42c-11e6-9e14-6c02068be1a5.png">

I cannot reproduce this in v0.11.1 - can you try a reinstall?

**Comment by dertuxmalwieder** [comment] 2016-11-06 14:39
It already was a clean installation.

I use the classic start menu though. Maybe this works different?

**Comment by vktr** [comment] 2016-11-06 14:41
Oh ok, let me check with the classic menu 😄

**Comment by vktr** [comment] 2016-11-06 14:49
<img width="303" alt="screenshot 2016-11-06 15 46 14" src="https://cloud.githubusercontent.com/assets/1491824/20038690/6cb4d29c-a438-11e6-9c03-4c3ababb12e2.png">
<img width="261" alt="screenshot 2016-11-06 15 47 34" src="https://cloud.githubusercontent.com/assets/1491824/20038691/6cccaae8-a438-11e6-9260-747859f61826.png">
<img width="252" alt="screenshot 2016-11-06 15 48 01" src="https://cloud.githubusercontent.com/assets/1491824/20038692/6ce0e328-a438-11e6-8a3b-e233dd78d53b.png">

I can't seem to reproduce the error you are describing. This is with the classic start menu provided by classicshell.net.

**Comment by dertuxmalwieder** [comment] 2016-11-06 14:50
Hmm. Why did it fail for me then?

**Comment by vktr** [comment] 2016-11-06 14:54
I'm unsure - perhaps a repair of the Classic Shell would solve something. Either way - closing this since I don't think the problem is in PicoTorrent.

**Closed by vktr** 2016-11-06 14:54 UTC
Labels: bug
