### ISSUE TITLE
Rechecking torrents after windows restart

### ISSUE THREAD

**Issue by birkoffe** [picotorrent/picotorrent#407] opened 2017-01-22 04:10 UTC
If I rerestart Windows with running picotorrent, after next picotorrent start all torrents go on rechecking.
If I exit picotorrent nornally there are no problems.

Picotorrent does not correctly handle windows shutdown?

Pico 0.12.0, windows 10x64

**Comment by dza89** [comment] 2017-01-22 13:35
With me they don't even just start rechecking but Picotorrent starts redownloading previous completed torrents.

**Comment by vktr** [comment] 2017-01-23 08:11
Thanks for the report! I'll look into it.

**Comment by vktr** [comment] 2017-01-26 10:59
@dza89 Are you sure they start redownloading? Sounds odd since data is written on the fly and not cached (at least not for a noticable time period). Re-checking looks similar to downloading (with a progress bar and all), might it be that you saw that?

**Comment by dza89** [comment] 2017-01-26 11:23
@vktr I will try reproduce the issue tonight and show you.

**Comment by HarshaThota** [comment] 2017-01-27 04:07
@vktr I had the same issue as @dza89. I had Windows shutdown unexpectedly and when I restarted PicoTorrent started downloading the torrents again. 

Running version 0.12.0 on Windows 10 (on the Insider builds).

**Comment by vktr** [comment] 2017-01-27 11:01
I'll do some testing tonight.

**Comment by dza89** [comment] 2017-02-04 09:15
@vktr I wasn't able to reproduce the issue. So at this point you shouldn't put any effort in it.

**Comment by birkoffe** [comment] 2017-02-06 12:48
Ups.

I grad to hear that @dza89 has all well.
But I made issue and my problem still here.

**Comment by vktr** [comment] 2017-02-06 12:49
Sorry 😄 It gets confusing sometimes.

**Comment by dza89** [comment] 2017-02-12 11:49
@vktr 
![capture](https://cloud.githubusercontent.com/assets/20373984/22861776/93ad0834-f121-11e6-9152-a16fe0721257.PNG)

Windows requested an reboot after updates. I clicked yes with picotorrent running and here you can see the result after reboot. (Background is file explorer, foreground is pico, file = file)

**Comment by vktr** [comment] 2017-02-13 15:24
@dza89 What is the issue? Was the file 100% completed before the restart?

**Comment by pokexpert** [comment] 2017-07-02 10:18
I had a similar issue right now, i downloaded yesterday 42GB on a 65GB torrent and today it restarted from scratch !

**Comment by janpieterz** [comment] 2017-08-17 09:06
I see to keep having this too. Most often seem to happen with torrents I've paused as well, showing completed, on next startup they 'forget' their completed and paused status, going back to Stalled / seeding.

**Comment by dza89** [comment] 2018-10-21 07:54
@pyorokun7 
Nope, I think that's the same issue. I think the issues lies with pico_state_message.rst.  I will try to reproduce the issue this week.

**Comment by vktr** [comment] 2018-12-06 15:32
Hi, sorry you're experiencing this issue. I'll see if I can put some more effort in hunting down the problems you are experiencing!

**Comment by moritz1000** [comment] 2019-10-15 18:06
The same thing happens when you pause a torrent and use a VPN kill switch. When I start PicoTorrent again the paused torrent starts on it's own. It only keeps the pause status when I properly close PicoTorrent.

**Comment by vktr** [comment] 2019-10-15 18:06
What does the VPN kill switch do? Terminate the PicoTorrent process?

**Comment by moritz1000** [comment] 2019-10-15 19:28
Yes

**Comment by Darth-Carrotpie** [comment] 2019-12-21 22:26
Same issue. Also when checking, PC proceeds to horribly lag, due to all of the RAM (16Gig)/cpu being eatin by Pico

**Comment by Tall-Lobster** [comment] 2020-01-17 00:27
Dear @vktr, this was occurring before update 0.18.0, but now it seems to be solved for version 0.18.0 for me, but of course I have not been using it as much so I will now have it to automatically startup with windows. Before the issue also occurred regardless of restarting windows or closing picotorrent that reopening it.

**Comment by Tall-Lobster** [comment] 2020-01-18 08:26
Dear @vktr , the error is still occuring even after the update to 0.18.0, but also this error occurs after one of the torrent files is updated to including the required files, and when you restart the applicaiton or restart the computer it goes to a view way before the latest download.

**Comment by vktr** [comment] 2020-01-19 18:43
Got it - I'll do a check.

**Closed** 2020-09-26 19:10 UTC
Labels: bug
