### ISSUE TITLE
When PicoTorrent is running and the .torrent file is opened from Explorer, nothing happens

### ISSUE THREAD

**Issue by Rakleed** [picotorrent/picotorrent#728] opened 2019-10-25 07:34 UTC
When PicoTorrent is running and the .torrent file is opened from Explorer, nothing happens. Although a window should open in PicoTorrent to add a torrent with information about it. I have selected by default that all torrent files should open in PicoTorrent. And if PicoTorrent is closed, then when you open the .torrent file, the window for adding a torrent opens.

**Comment by vktr** [comment] 2019-10-25 21:54
I can't seem to reproduce this - I've tried to provoke the error both when PicoTorrent is running and when it is not, as well as with UTF16 file names. The add torrent dialog shows as expected in all cases.

**Comment by Rakleed** [comment] 2019-10-26 09:19
@vktr I was now able to reproduce the problem on another device. And apparently this is due to the fact that I was updating from version 0.15 (and I updated to all versions in a row - 0.16, 0.16.1 and 0.17). Because now I tried to uninstall the application and reinstall it, and there is no more problem.

**Comment by moritz1000** [comment] 2019-10-28 15:29
I had the same issue (but updated from 0.16). I uninstalled Picotorrent and reinstalled it but it did not fix the issue. I downloaded http://defaultprogramseditor.com/ and manually deleted the .torrent file association with Picotorrent since I could only change it to a different program and not delete it in Windows. Now everything works again.

**Comment by moritz1000** [comment] 2019-10-28 15:44
I have the same issue. I uninstalled Picotorrent and reinstalled it but it did not fix the issue. I tried to fix it manually with http://defaultprogramseditor.com/ and deleting the .torrent file association with Picotorrent but that also did not work.

Maybe it has something to do with the encrypt_config_file setting from version PicoTorrent-0.15.0 which is not available in PicoTorrent-0.17.0 anymore? I think so because no matter what I changed in the Proxy settings after the reinstall I was still connected to my Proxy even though it looked like as if PicoTorrent lost all my settings when starting 0.17.0 for the first time. For the time being I went back to 0.15.0

**Comment by Rakleed** [comment] 2019-11-07 09:56
At the moment, on the computer, I again had this problem.

**Comment by Tall-Lobster** [comment] 2019-12-02 01:24
I am also facing the same issue, my solution is i drag the file from firefox download directly to picotorrent. But yes 25 days from @Rakleed's last comment and I am facing this issue.

**Comment by vktr** [comment] 2019-12-11 09:32
Hey guys! I'll take a look at this.

**Comment by Darth-Carrotpie** [comment] 2019-12-21 22:23
Same issue, but with chrome. Trying to launch a downlaoded torrent file from explorer then also wont launch / hook to pico

**Comment by Isharoth** [comment] 2020-02-10 23:53
The same issue on 0.18.0. Also the same problem with magnet links opened from web browser.

**Comment by vktr** [comment] 2020-09-10 22:47
Closing this as I believe it is fixed in the latest version. Feel free to reopen or file another issue if I'm wrong :)

**Closed by vktr** 2020-09-10 22:47 UTC
Labels: bug
