### ISSUE TITLE
Bulk operations crash picotorrent consistently

### ISSUE THREAD

**Issue by annogram** [picotorrent/picotorrent#795] opened 2020-01-03 01:53 UTC
Trying to perform any bulk cancellations crashes picotorrent.

Reproduce by:

1. Selecting more than one torrent
2. right click and click remove
3. crash should occur 

Device info:

Windows 10 home edition

No errors come up in event viewer

**Comment by erayrafet** [comment] 2020-01-07 19:06
Additionally, the app tends to delete unselected and unfinished downloads but keeps them in the list and begins re-downloading the next time I start it. It is easily reproducible.

**Comment by VideoPlayerCode** [comment] 2020-01-10 08:05
@erayrafet Please make a separate ticket for unrelated issues like that.

**Comment by erayrafet** [comment] 2020-01-10 10:01
@VideoPlayerCode It's not exactly unrelated because it is still a bulk action.

**Comment by vktr** [comment] 2020-01-12 19:58
@erayrafet Can you give more detail? I can reproduce the original issue but not yours.

**Comment by erayrafet** [comment] 2020-01-13 08:09
Let's say that I have 5 torrents - 2 of them are finished and the other 3 are still running. If I try to delete/remove the downloaded torrents, the app crashes and upon the next launch, it starts downloading the unfinished ones from scratch.

**Comment by vktr** [comment] 2020-01-19 18:52
@erayrafet Can you check if the issue is resolved with #803?

**Comment by erayrafet** [comment] 2020-01-19 18:55
@vktr Sure. I'll report back tomorrow.

**Comment by erayrafet** [comment] 2020-01-19 18:56
Build? I can't compile.

**Comment by vktr** [comment] 2020-01-19 18:59
Sorry, it's not straight forward where to find the builds :smiley: Here's a direct link to the x64 artifacts, https://ci.appveyor.com/project/picotorrent/picotorrent/builds/30060196/job/5rf4685xjv75vog7/artifacts

**Comment by erayrafet** [comment] 2020-01-20 05:53
Works like a charm! No random exits and no data loss.

**Comment by erayrafet** [comment] 2020-01-20 05:55
Thanks!
By the way, do you have plans for incorporating a different UI design, 'cause it looks very dated right now?

**Comment by vktr** [comment] 2020-01-28 22:22
Good to hear @erayrafet 😄 There are some ideas around allowing some CSS styling to have different themes, but nothing concrete. The CSS would be the built-in CSS engine in Qt which allows styling of elements.

**Closed by vktr** 2020-01-28 22:22 UTC
Labels: bug
