### ISSUE TITLE
Cannot set priority

### ISSUE THREAD

**Issue by ghost** [picotorrent/picotorrent#748] opened 2019-11-02 17:28 UTC
With the new version(I currently have the latest 0.17) I can no longer set priority to individual files when downloading + I can not set priority at all. So the latter probably causes the former.

**Comment by nonpcnpc** [comment] 2019-11-03 12:03
When I am adding new torrent, I can set the priority and when I have some "do not download" files I can then change their priority - once. To me, it looks like there is some kind of UI re-render when I click on the file and get the context menu and the file loses focus - that is why the priority won't be set.

**Comment by nonpcnpc** [comment] 2019-11-03 12:07
Ah, I got it. So the UI is re-rendered every second when the torrent is active. Once it is paused or simply not-stared(completed...) the re-rendering is turned of and I can set priority to the files. That is why I was able to set priority for "do not download" files, because the torrent was already finished, so it has nothing to do with the set priority but with the torrent being active or not.

**Comment by vktr** [comment] 2019-11-03 19:04
Hey! Thanks for the detailed investigation! I'll have a look and see if I can reproduce it.

**Comment by vktr** [comment] 2019-11-03 19:27
I can't reproduce this - all my attempts at re-prioritizing files were successful. Can you record a GIF (or similar) showing the issues you're having?

**Comment by nonpcnpc** [comment] 2019-11-04 16:28
click on any active torrent, down below select the "files" tab. then click on any of the files. it will get highlighted. wait a second, the file should no longer be highlighted.

**Comment by vktr** [comment] 2019-11-04 18:53
Is this in 0.17? I can't reproduce this on my end. Which Windows version are you running?

**Comment by nonpcnpc** [comment] 2019-11-04 19:23
win10x64 pro

**Comment by nonpcnpc** [comment] 2019-11-08 15:26
I have observed another side effect of that re-rendering bug. When the torrent has directories and I expand one, after a second/nex tick when the window is re-rendered, the directory collapses back.

**Comment by vktr** [comment] 2019-11-08 20:23
Can you try the latest build on AppVeyor? https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/wc0up4ciiaf5ua3l/artifacts

**Comment by nonpcnpc** [comment] 2019-11-09 10:16
sure, just give me link to compiled binary

**Comment by vktr** [comment] 2019-11-09 10:24
https://ci.appveyor.com/project/picotorrent/picotorrent/build/job/oq92fkr73ojxsrhh/artifacts

**Comment by nonpcnpc** [comment] 2019-11-09 15:39
both issues are fixed in that one.

**Comment by vktr** [comment] 2019-11-09 17:55
It's the same code in both so I guess it's resolved 😃 I'm setting this up to be closed when 0.17 is released.

**Comment by wintercounter** [comment] 2019-11-10 19:21
For mer it's the same with 0.17. Simply the file selection being lost on every second.

**Comment by vktr** [comment] 2019-11-10 19:23
@wintercounter Do you have the same issue even in the latest build linked above?

**Comment by VideoPlayerCode** [comment] 2019-12-04 06:56
@vktr Same here. I have v0.17.0 installed from https://chocolatey.org/packages/picotorrent#versionhistory (which says "Saturday, October 26, 2019")

During downloads, the file list refreshes itself every second. This refreshing clears all selections, even when the menu has already been opened (ie. via right-clicking a single file). So you literally cannot change priority at all, because by the time the right click menu is open, the file list itself has already refreshed and cleared the selection.

However, the special build above fixes it. :-)

**Comment by nonpcnpc** [comment] 2019-12-04 09:35
What is the ETA of next release?

**Comment by nonpcnpc** [comment] 2019-12-20 14:25
🤔

**Comment by vktr** [comment] 2019-12-22 13:07
It should be out after the holidays - I'm aiming towards a mid-january release.

**Comment by spoonpaw** [comment] 2019-12-23 19:42
i'm having the same issue, windows 10, v0.17.0

**Comment by Rakleed** [comment] 2019-12-24 10:18
@spoonpaw You should install the latest build from AppVeyor https://ci.appveyor.com/project/picotorrent/picotorrent/builds/29710681/job/3j5o7hiwdiqvm83i/artifacts, because it solved the problem. And the developer plans the next release of the application in mid-January, if there are no problems.

**Comment by spoonpaw** [comment] 2019-12-24 20:14
@Rakleed thanks! this has resolved the issue for me!

**Comment by vktr** [comment] 2020-02-01 20:10
Closing since it has been released.

**Closed by vktr** 2020-02-01 20:10 UTC
Labels: bug
