### ISSUE TITLE
Crash when download starts

### ISSUE THREAD

**Issue by abalteaux** [picotorrent/picotorrent#614] opened 2018-05-01 07:22 UTC
With the latest release (0.15.0, Windows 10 Home x64), I can't seem to get past the fetching of magnet links metadata / get the download to start with a torrent file. The app crashes then.
I attached the event file log corresponding to it, please tell me if there's anything else you might need!

[crash-picotorrent.zip](https://github.com/picotorrent/picotorrent/files/1963195/crash-picotorrent.zip)

**Comment by vktr** [comment] 2018-05-01 08:10
Can you attach the magnet link or torrent file that fails? Or send it to
viktor@viktorelofsson.se

On Tue, May 1, 2018, at 09:22, Aurélien Balteaux wrote:
> With the latest release (0.15.0, Windows 10 Home x64), I can't seem to
> get past the fetching of magnet links metadata / get the download to
> start with a torrent file. The app crashes then.>  I attached the event file log corresponding to it, please tell me if
>  there's anything else you might need!> crash-picotorrent.zip[1]


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].> 


Links:

  1. https://github.com/picotorrent/picotorrent/files/1963195/crash-picotorrent.zip
  2. https://github.com/picotorrent/picotorrent/issues/614

**Comment by abalteaux** [comment] 2018-05-01 13:32
Sure thing, the magnet link is magnet:?xt=urn:btih:60a06787f4d3fcf511a5425c837a9364684c8326&dn=Silicon.Valley.S05E06.1080p.WEB.H264-DEFLATE%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710

Thanks!

**Comment by vktr** [comment] 2019-03-20 22:01
I'm going through older issues in preparation of the next release and I can't reproduce this issue in #672 which is the base for the next version (0.16). Closing this for now.

**Closed by vktr** 2019-03-20 22:01 UTC
