### ISSUE TITLE
Details window to be resizable and remember its size

### ISSUE THREAD

**Issue by Eldaw** [picotorrent/picotorrent#455] opened 2017-07-03 20:09 UTC
It would be helpful if the Details window allowed itself to be resized. And to remember its size (not only when closing and opening it again during a session, but also between sessions, i.e. after quitting and restarting the application).

Same for the sizes of the columns. In the Details window as well as the main application window.

**Comment by olivierchatry** [comment] 2017-07-03 20:45
Duplicate of #448 if you can close this one :)

**Comment by Eldaw** [comment] 2017-07-03 20:47
Duplicate? No. That other one mentions the window remembering its position on the monitor. This one is about the size of the window itself being able to be resized. Furthermore, this one is also about the column sizes.

**Comment by vktr** [comment] 2017-07-03 20:52
Yeah, I see what you're getting at 😄 Would you mind openening another issue for the column sizes? It's easy to forget part of an issue if they contain more than one request.

**Comment by olivierchatry** [comment] 2017-07-03 20:56
Ha yeah sorry, jumped the gun :(.

**Comment by vktr** [comment] 2018-03-02 22:29
Not applicable since #486

**Closed by vktr** 2018-03-02 22:29 UTC
