### ISSUE TITLE
Multi-language instalelr

### ISSUE THREAD

**Issue by bovirus** [picotorrent/picotorrent#1101] opened 2021-01-06 11:48 UTC
@vktr 

How can help you to enable multi-language installer?

**Comment by AHOHNMYC** [comment] 2021-02-25 16:18
Seems like duplicate of #727.

**Comment by vktr** [comment] 2021-02-26 06:47
Closing this in favor of #727. We'll add translations to the installer as soon as I figured out how to integrate it with Weblate 😄

**Closed by vktr** 2021-02-26 06:47 UTC
Labels: installer
