### ISSUE TITLE
Program forget last state when crash. Runtime error when attempting recheck torrent while other torrent is rechecking

### ISSUE THREAD

**Issue by slrslr** [picotorrent/picotorrent#646] opened 2018-08-23 20:59 UTC
0.15.0

Hello, when i attempt to recheck torrent while other torrent is already rechecking, then i see Runtime error and also other crash where WIndows 10 invite me to close the app, No other option.

And when i reopen app, then it forgets torrents i rechecked during the previous session.

THis issue with rechecking does not happen always apparently. But most important think is that Pico Torrent do not remember my changes, rechecks for whole previous session.

**Comment by vktr** [comment] 2019-06-12 15:28
Can't reproduce this in #672 - closing this and should it happen again when 0.16 has been released, feel free to reopen 😄

**Closed by vktr** 2019-06-12 15:28 UTC
Labels: bug
